# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from locomotion_robot_pkg/sub_move.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class sub_move(genpy.Message):
  _md5sum = "1167768357c0e474a6f4a552c72b1fa2"
  _type = "locomotion_robot_pkg/sub_move"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String primitive
std_msgs/Int32 distance
std_msgs/Int32 angle
================================================================================
MSG: std_msgs/String
string data

================================================================================
MSG: std_msgs/Int32
int32 data"""
  __slots__ = ['primitive','distance','angle']
  _slot_types = ['std_msgs/String','std_msgs/Int32','std_msgs/Int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       primitive,distance,angle

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sub_move, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.primitive is None:
        self.primitive = std_msgs.msg.String()
      if self.distance is None:
        self.distance = std_msgs.msg.Int32()
      if self.angle is None:
        self.angle = std_msgs.msg.Int32()
    else:
      self.primitive = std_msgs.msg.String()
      self.distance = std_msgs.msg.Int32()
      self.angle = std_msgs.msg.Int32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.primitive.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.distance.data, _x.angle.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.primitive is None:
        self.primitive = std_msgs.msg.String()
      if self.distance is None:
        self.distance = std_msgs.msg.Int32()
      if self.angle is None:
        self.angle = std_msgs.msg.Int32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.primitive.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.primitive.data = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.distance.data, _x.angle.data,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.primitive.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.distance.data, _x.angle.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.primitive is None:
        self.primitive = std_msgs.msg.String()
      if self.distance is None:
        self.distance = std_msgs.msg.Int32()
      if self.angle is None:
        self.angle = std_msgs.msg.Int32()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.primitive.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.primitive.data = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.distance.data, _x.angle.data,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
